### PR TITLE
added AARE response diagnostic to GXDLMSClient

### PR DESCRIPTION
**Pull request by gstamac**

### CODE REVIEW

**Comment by gstamac** [comment]
Will this ever be merged?

**Comment by gurux01** [comment]
Hi,

Sorry for slow reply. If resultComponent != AssociationResult.Accepted && resultDiagnosticValue != SourceDiagnostic.None exception is throw. If you catch GXDLMSException you can already get this information from there. For this reason we'll not merge this.

**Comment by gstamac** [comment]
If I receive the following frame
7EA026210201304F22E6E7006117A109060760857405080101A203020101A305A10302010DAE4F7E
it contains
association-result = rejected-permanent, association-result-diag acse-service-user = authentication-failure
but parseAareResponse succeeds. Am I missing something?

**Comment by gstamac** [comment]
I see now. Since there is no User-information in the AARE the code you are talking about isn't executed.

**Comment by gstamac** [comment]
This check should be moved to the end of the parsePDU2 function.

**Comment by gstamac** [comment]
Created another pull request.

**Pull request closed without merging**
